In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

# Project paths
BASE_DIR = Path.cwd().parent

POSTS_PATH = BASE_DIR / "data" / "raw" / "Social_Engine_Posts_Corrupted.csv"
USERS_PATH = BASE_DIR / "data" / "raw" / "Social_Engine_Users.csv"

# Load raw datasets
posts = pd.read_csv(POSTS_PATH)
users = pd.read_csv(USERS_PATH)

print("Posts shape:", posts.shape)
print("Users shape:", users.shape)

Posts shape: (12360, 8)
Users shape: (1500, 5)

In [2]:
# ============================================
# DATA VORTEX - PHASE 1
# Initial Dataset Audit
# ============================================

print("=" * 60)
print("POSTS DATASET")
print("=" * 60)

print("\nShape:")
print(posts.shape)

print("\nColumns:")
print(posts.columns.tolist())

print("\nData Types:")
print(posts.dtypes)

print("\nMissing Values:")
print(posts.isna().sum())

print("\nDuplicate Rows:")
print(posts.duplicated().sum())

print("\n" + "=" * 60)
print("USERS DATASET")
print("=" * 60)

print("\nShape:")
print(users.shape)

print("\nColumns:")
print(users.columns.tolist())

print("\nData Types:")
print(users.dtypes)

print("\nMissing Values:")
print(users.isna().sum())

print("\nDuplicate Rows:")
print(users.duplicated().sum())

============================================================
POSTS DATASET
============================================================

Shape:
(12360, 8)

Columns:
['post_id', 'user_id', 'platform', 'text_content', 'timestamp', 'likes', 'shares', 'comments']

Data Types:
post_id             str
user_id             str
platform            str
text_content        str
timestamp           str
likes           float64
shares            int64
comments          int64
dtype: object

Missing Values:
post_id            0
user_id            0
platform        1846
text_content    1746
timestamp          0
likes           1858
shares             0
comments           0
dtype: int64

Duplicate Rows:
360

============================================================
USERS DATASET
============================================================

Shape:
(1500, 5)

Columns:
['user_id', 'location', 'language', 'account_created', 'follower_count']

Data Types:
user_id              str
location             str
language             str
account_created      str
follower_count     int64
dtype: object

Missing Values:
user_id            0
location           0
language           0
account_created    0
follower_count     0
dtype: int64

Duplicate Rows:
0

In [3]:
# Numerical summary of the posts dataset
posts.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
post_id,12360,12000,18872bs3czdy,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
user_id,12360,1500,user_zqv2vrf5,22,NaN,NaN,NaN,NaN,NaN,NaN,NaN
platform,10514,5,YouTube,2136,NaN,NaN,NaN,NaN,NaN,NaN,NaN
text_content,10614,10225,NULL\n\n,24,NaN,NaN,NaN,NaN,NaN,NaN,NaN
timestamp,12360,8839,30-05-2024,21,NaN,NaN,NaN,NaN,NaN,NaN,NaN
likes,10502.0,NaN,NaN,NaN,2247.075795,1797.342958,-4987.0,1038.25,2387.0,3664.0,5000.0
shares,12360.0,NaN,NaN,NaN,1005.867557,574.734542,0.0,509.0,1016.0,1499.0,2000.0
comments,12360.0,NaN,NaN,NaN,504.081958,288.796752,0.0,252.0,503.0,755.0,1000.0

In [6]:
# Unique values in important categorical columns
# Unique values in categorical columns that actually exist

categorical_columns = posts.select_dtypes(include=["object"]).columns

for column in categorical_columns:
    print(f"\n--- {column.upper()} ---")
    print(posts[column].value_counts(dropna=False))

--- POST_ID ---
post_id
18872bs3czdy    3
v3q8wgq6f29o    3
am8fodsgv86c    3
4fgbp1fc2w0z    3
utkzs6e0k0pe    3
               ..
7nar7yotf6u4    1
qokoc4of26wk    1
jraym4uws51h    1
21idyx41b5v4    1
2e9glp0jqtl1    1
Name: count, Length: 12000, dtype: int64

--- USER_ID ---
user_id
user_zqv2vrf5    22
user_nfo3ih5u    19
user_n0ok02rt    19
user_8wk0j5ae    19
user_0irp4abu    18
                 ..
user_0riqrfz9     2
user_cbswmk3b     2
user_kktxhpej     2
user_n60azzwm     1
user_mkqbrm43     1
Name: count, Length: 1500, dtype: int64

--- PLATFORM ---
platform
YouTube      2136
Facebook     2135
Twitter      2119
Reddit       2086
Instagram    2038
NaN          1846
Name: count, dtype: int64

--- TEXT_CONTENT ---
text_content
NaN                                                                                                                                                    1746
NULL\n\n                                                                                                                                                 24
NULL&amp;                                                                                                                                                21
NULLÃ©                                                                                                                                                   19
NULL<div>                                                                                                                                                17
                                                                                                                                                       ...
How do I fix about Google's Pixel 8? @StyleGuide #Quality, #Sale, #CustomerService Really interested in hearing your thoughts!                            1
My one month review of Toyota RAV4: As expected. #ProductLaunch, #Food, #SpecialOffer Would love to get your feedback!                                    1
Just unboxed my new Highlander from Toyota. Disappointed with the quality. Delighted #Reviews, #Quality Really interested in hearing your thoughts!       1
Just unboxed my new Vision Pro from Apple. Worth every penny. Super excited #Discount, #Beauty                                                            1
My six months review of Coca-Cola Coke Zero: Wouldn't recommend. #Tech, #TrendAlert Curious about your experience too.                                    1
Name: count, Length: 10226, dtype: int64

--- TIMESTAMP ---
timestamp
30-05-2024             21
13-01-2025             20
25-02-2025             20
11-10-2024             17
22-01-2025             17
                       ..
1744134748              1
2024-11-25T12:57:51     1
2025-02-19T00:17:20     1
1742309918              1
2025-02-26T19:28:33     1
Name: count, Length: 8839, dtype: int64

C:\Users\Jivan\AppData\Local\Temp\ipykernel_32680\3176531014.py:4: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = posts.select_dtypes(include=["object"]).columns

In [7]:
# Clean categorical-column detection for pandas 3.x

categorical_columns = posts.select_dtypes(include=["str", "object"]).columns

print("Categorical columns found:")
print(list(categorical_columns))

for column in categorical_columns:
    print(f"\n{'=' * 50}")
    print(f"{column.upper()}")
    print(f"{'=' * 50}")
    
    print("Unique values:", posts[column].nunique(dropna=True))
    print("Missing values:", posts[column].isna().sum())
    print("\nTop 10 values:")
    print(posts[column].value_counts(dropna=False).head(10))

Categorical columns found:
['post_id', 'user_id', 'platform', 'text_content', 'timestamp']

==================================================
POST_ID
==================================================
Unique values: 12000
Missing values: 0

Top 10 values:
post_id
18872bs3czdy    3
v3q8wgq6f29o    3
am8fodsgv86c    3
4fgbp1fc2w0z    3
utkzs6e0k0pe    3
vcx4pccxtll6    3
ajzrensvmuqq    3
3bj6zmt6mp0m    3
7f0wdauzbj89    2
i6io9jo0vpxa    2
Name: count, dtype: int64

==================================================
USER_ID
==================================================
Unique values: 1500
Missing values: 0

Top 10 values:
user_id
user_zqv2vrf5    22
user_nfo3ih5u    19
user_n0ok02rt    19
user_8wk0j5ae    19
user_0irp4abu    18
user_q3vs0uj7    18
user_8w06w1qu    17
user_cntp6452    17
user_xetn4exw    17
user_wyeb78qv    16
Name: count, dtype: int64

==================================================
PLATFORM
==================================================
Unique values: 5
Missing values: 1846

Top 10 values:
platform
YouTube      2136
Facebook     2135
Twitter      2119
Reddit       2086
Instagram    2038
NaN          1846
Name: count, dtype: int64

==================================================
TEXT_CONTENT
==================================================
Unique values: 10225
Missing values: 1746

Top 10 values:
text_content
NaN                                                                                                                                              1746
NULL\n\n                                                                                                                                           24
NULL&amp;                                                                                                                                          21
NULLÃ©                                                                                                                                             19
NULL<div>                                                                                                                                          17
NULL<br>                                                                                                                                           13
Loving it with my new Coca-Cola Cherry from Coca-Cola! It's okay. #MustHave, #Lifestyle, #SpecialOffer Curious about your experience too.<br>       3
Just saw an ad for Apple Mac Mini during the CyberMonday. Wouldn't recommend. #Affordable, #Fitness, #Tech                                          3
Comparing Microsoft Xbox Elite Controller to the competition. Highly recommend. #Food Curious about your experience too.                            3
Anyone have tips about Pepsi's Crystal Pepsi? @BrandCEO, @CustomerService #Sale, #Reviews, #Health Curious about your experience too.               3
Name: count, dtype: int64

==================================================
TIMESTAMP
==================================================
Unique values: 8839
Missing values: 0

Top 10 values:
timestamp
30-05-2024    21
13-01-2025    20
25-02-2025    20
11-10-2024    17
22-01-2025    17
20-04-2025    17
12-07-2024    17
24-01-2025    16
14-08-2024    16
08-02-2025    16
Name: count, dtype: int64

In [8]:
# Numerical columns audit

numeric_columns = posts.select_dtypes(include="number").columns

print("Numerical columns:")
print(list(numeric_columns))

for column in numeric_columns:
    print(f"\n{'=' * 50}")
    print(f"{column.upper()}")
    print(f"{'=' * 50}")
    
    print("Missing:", posts[column].isna().sum())
    print("Minimum:", posts[column].min())
    print("Maximum:", posts[column].max())
    print("Negative values:", (posts[column] < 0).sum())

Numerical columns:
['likes', 'shares', 'comments']

==================================================
LIKES
==================================================
Missing: 1858
Minimum: -4987.0
Maximum: 5000.0
Negative values: 525

==================================================
SHARES
==================================================
Missing: 0
Minimum: 0
Maximum: 2000
Negative values: 0

==================================================
COMMENTS
==================================================
Missing: 0
Minimum: 0
Maximum: 1000
Negative values: 0

In [9]:
# Inspect negative likes

negative_likes = posts[posts["likes"] < 0]

print("Negative likes count:", len(negative_likes))

negative_likes[
    ["post_id", "user_id", "platform", "likes", "shares", "comments"]
].head(20)

Negative likes count: 525

          post_id        user_id   platform   likes  shares  comments
20   mbykzpzh1l1y  user_750rlmnw        NaN -4812.0    1777       553
94   wal886ggp7kg  user_e3cwapff    YouTube -1795.0     454       350
153  38tm1xfxxsdi  user_r7o639pp  Instagram -3707.0     957        49
163  yktgh97ttawi  user_ral75hq0    Twitter -4543.0     363       703
188  loscndnlqi7b  user_xyvxp8vz    Twitter -3194.0     904       378
192  hvjh643oxb8e  user_puypdmp1    YouTube -3616.0    1728       363
197  0c0tc7wbhqdu  user_m2ziq5ox  Instagram -1165.0     709       403
263  dnhsqcx3t94w  user_oknxkzax    Twitter  -738.0     980       503
266  5fbt4nzjxol9  user_t2e8zk5w     Reddit  -851.0    1959       185
268  whsvb3faauwf  user_uod57rwt   Facebook -1205.0    1413       976
273  849vopmpaov5  user_wawwrvtc    YouTube -1007.0     810       228
283  5yja32qo8r5v  user_nfgm6ygg   Facebook -4668.0    1582       209
325  tpqh5r4b6wbj  user_lkkaeb12        NaN -4743.0    1267       845
330  6pnyn4zvt821  user_5idgm0pl        NaN  -940.0    1075       142
331  d7mugp06qohp  user_4wxjuaif    Twitter  -295.0     322       637
459  bmsl9n7piai5  user_wawwrvtc  Instagram -3964.0    1447       997
463  knwr2mg0yme4  user_nq5irbxf        NaN -2786.0     428       693
508  do7er5bxtgtz  user_siuvpkza        NaN -1205.0     806       513
529  7xz8eesy39yk  user_yn18x47n  Instagram -4307.0    1959       700
583  ri5if1n91f7n  user_7tzoxyvz        NaN -1919.0    1301       854

In [10]:
# Inspect missing likes

missing_likes = posts[posts["likes"].isna()]

print("Missing likes count:", len(missing_likes))

missing_likes[
    ["post_id", "user_id", "platform", "shares", "comments"]
].head(20)

Missing likes count: 1858

          post_id        user_id  platform  shares  comments
2    dvvhg8eel45x  user_nfo3ih5u       NaN    1410       839
6    19ys654yi1if  user_27aje6ur  Facebook    1578       514
22   y2s75tpyz8xz  user_084pfdpp   YouTube     951       243
29   126l8riadfj2  user_n3yjfvxy   YouTube     808       995
32   04hiukoawu9c  user_n0ok02rt    Reddit     166       884
36   aq3dtllhs6dr  user_2a5282v7   YouTube     197        21
37   fcvapj7471ky  user_74hhbvxk   YouTube    1071       439
46   csdwcp9j1cct  user_7ynl9cyw   YouTube    1787       591
65   p7h083r7vums  user_8gk2so0l   YouTube     675       572
69   1zq65wyz8gzg  user_frdud4v4   Twitter      36       286
70   62q3q1y4rvye  user_ja1dmtpu  Facebook    1594       365
77   o70j2gzc3kkw  user_ztrgkwrt  Facebook    1035       892
80   5gyyfd2wv95z  user_3o7w66o2       NaN    1529       655
98   wr0jvpift9jk  user_a3njsw7g    Reddit     762       308
106  dx6f46fo6luu  user_8cnur462  Facebook    1792       625
125  yo588lfy0mob  user_4mf7je2u  Facebook    1760       541
128  wrpuf437gh64  user_gq0rypar    Reddit     361       656
133  nap5vkbmyrys  user_01mu2x1s   Twitter    1975       155
140  kz3gmtrvjl4i  user_m80j4x3i       NaN    1756       495
152  8kbjny4qot2q  user_acrnl9py   Twitter     988       674

In [11]:
# Statistical comparison

print("Normal likes:")
print(posts[posts["likes"] >= 0]["likes"].describe())

print("\nNegative likes:")
print(posts[posts["likes"] < 0]["likes"].describe())

Normal likes:
count    9977.000000
mean     2494.621730
std      1437.920657
min         0.000000
25%      1241.000000
50%      2505.000000
75%      3725.000000
max      5000.000000
Name: likes, dtype: float64

Negative likes:
count     525.000000
mean    -2457.240000
std      1426.570583
min     -4987.000000
25%     -3640.000000
50%     -2388.000000
75%     -1205.000000
max       -11.000000
Name: likes, dtype: float64

In [12]:
# ============================================
# CHECK FOR NEGATIVE-LIKE CORRUPTION PATTERN
# ============================================

negative = posts[posts["likes"] < 0].copy()

negative["absolute_likes"] = negative["likes"].abs()

print("Negative likes:", len(negative))

print("\nAbsolute value statistics:")
print(negative["absolute_likes"].describe())

print("\nDo absolute values stay within valid range?")
print(
    "All between 0 and 5000:",
    negative["absolute_likes"].between(0, 5000).all()
)

print("\nFirst 20 corrupted values:")
print(
    negative[
        ["post_id", "likes", "absolute_likes", "shares", "comments"]
    ].head(20)
)

Negative likes: 525

Absolute value statistics:
count     525.000000
mean     2457.240000
std      1426.570583
min        11.000000
25%      1205.000000
50%      2388.000000
75%      3640.000000
max      4987.000000
Name: absolute_likes, dtype: float64

Do absolute values stay within valid range?
All between 0 and 5000: True

First 20 corrupted values:
          post_id   likes  absolute_likes  shares  comments
20   mbykzpzh1l1y -4812.0          4812.0    1777       553
94   wal886ggp7kg -1795.0          1795.0     454       350
153  38tm1xfxxsdi -3707.0          3707.0     957        49
163  yktgh97ttawi -4543.0          4543.0     363       703
188  loscndnlqi7b -3194.0          3194.0     904       378
192  hvjh643oxb8e -3616.0          3616.0    1728       363
197  0c0tc7wbhqdu -1165.0          1165.0     709       403
263  dnhsqcx3t94w  -738.0           738.0     980       503
266  5fbt4nzjxol9  -851.0           851.0    1959       185
268  whsvb3faauwf -1205.0          1205.0    1413       976
273  849vopmpaov5 -1007.0          1007.0     810       228
283  5yja32qo8r5v -4668.0          4668.0    1582       209
325  tpqh5r4b6wbj -4743.0          4743.0    1267       845
330  6pnyn4zvt821  -940.0           940.0    1075       142
331  d7mugp06qohp  -295.0           295.0     322       637
459  bmsl9n7piai5 -3964.0          3964.0    1447       997
463  knwr2mg0yme4 -2786.0          2786.0     428       693
508  do7er5bxtgtz -1205.0          1205.0     806       513
529  7xz8eesy39yk -4307.0          4307.0    1959       700
583  ri5if1n91f7n -1919.0          1919.0    1301       854

In [13]:
# ============================================
# RECOVER SIGN-FLIPPED LIKES
# ============================================

# Preserve original values for auditability
posts["likes_original"] = posts["likes"]

# Flag negative likes before correction
posts["likes_was_negative"] = posts["likes"] < 0

# Recover negative likes using absolute value
posts.loc[posts["likes"] < 0, "likes"] = (
    posts.loc[posts["likes"] < 0, "likes"].abs()
)

print("Negative likes recovered:", posts["likes_was_negative"].sum())

print("\nRemaining negative likes:")
print((posts["likes"] < 0).sum())

print("\nLikes statistics after recovery:")
print(posts["likes"].describe())

Negative likes recovered: 525

Remaining negative likes:
0

Likes statistics after recovery:
count    10502.000000
mean      2492.752999
std       1437.311007
min          0.000000
25%       1236.250000
50%       2500.000000
75%       3722.750000
max       5000.000000
Name: likes, dtype: float64

In [14]:
# ============================================
# INVESTIGATE MISSING LIKES PATTERN
# ============================================

likes_missing = posts["likes"].isna()

print("Total rows:", len(posts))
print("Missing likes:", likes_missing.sum())
print("Missing likes %:", round(likes_missing.mean() * 100, 2))

print("\nPlatform-wise likes analysis:")
platform_likes = posts.groupby(
    "platform",
    dropna=False
)["likes"].agg(
    total_rows="size",
    missing_likes="apply"
)

print(platform_likes)

Total rows: 12360
Missing likes: 1858
Missing likes %: 15.03

Platform-wise likes analysis:

TypeError: SeriesGroupBy.apply() missing 1 required positional argument: 'func'

In [15]:
# ============================================
# PLATFORM-WISE MISSING LIKES
# ============================================

platform_likes = posts.groupby(
    "platform",
    dropna=False
)["likes"].agg(
    total_rows="size",
    missing_likes=lambda x: x.isna().sum()
)

platform_likes["missing_rate_%"] = (
    platform_likes["missing_likes"]
    / platform_likes["total_rows"] * 100
).round(2)

print(platform_likes)

           total_rows  missing_likes  missing_rate_%
platform
Facebook         2135            331           15.50
Instagram        2038            300           14.72
Reddit           2086            297           14.24
Twitter          2119            329           15.53
YouTube          2136            336           15.73
NaN              1846            265           14.36

In [16]:
# ============================================
# MISSING vs AVAILABLE LIKES
# ============================================

likes_missing = posts["likes"].isna()

print("\nMissing vs Available likes:")
print(
    posts.groupby(likes_missing)[["shares", "comments"]]
    .mean()
)

print("\nSample rows with missing likes:")
print(
    posts[likes_missing][
        ["post_id", "user_id", "platform",
         "text_content", "shares", "comments"]
    ].head(15)
)

Missing vs Available likes:
            shares    comments
likes
False  1004.766997  503.196534
True   1012.088267  509.086652

Sample rows with missing likes:
          post_id        user_id  platform  \
2    dvvhg8eel45x  user_nfo3ih5u       NaN
6    19ys654yi1if  user_27aje6ur  Facebook
22   y2s75tpyz8xz  user_084pfdpp   YouTube
29   126l8riadfj2  user_n3yjfvxy   YouTube
32   04hiukoawu9c  user_n0ok02rt    Reddit
36   aq3dtllhs6dr  user_2a5282v7   YouTube
37   fcvapj7471ky  user_74hhbvxk   YouTube
46   csdwcp9j1cct  user_7ynl9cyw   YouTube
65   p7h083r7vums  user_8gk2so0l   YouTube
69   1zq65wyz8gzg  user_frdud4v4   Twitter
70   62q3q1y4rvye  user_ja1dmtpu  Facebook
77   o70j2gzc3kkw  user_ztrgkwrt  Facebook
80   5gyyfd2wv95z  user_3o7w66o2       NaN
98   wr0jvpift9jk  user_a3njsw7g    Reddit
106  dx6f46fo6luu  user_8cnur462  Facebook

                                          text_content  shares  comments
2    Just unboxed my new Highlander from Toyota. Ex...    1410       839
6    Fed up with my new iPhone 15 from Apple! Best ...    1578       514
22   Just saw an ad for Pepsi Pepsi Max during the ...     951       243
29   Has anyone else experienced connectivity issue...     808       995
32   Sad to report with my new Eero WiFi from Amazo...     166       884
36                                                 NaN     197        21
37   How do I fix about Nike's Air Max? @TechHelp, ...    1071       439
46   Has anyone else experienced connectivity issue...    1787       591
65   Just saw an ad for Samsung Neo QLED TV during ...     675       572
69   My three months review of Pepsi Diet Pepsi: It...      36       286
70                                                 NaN    1594       365
77                                                 NaN    1035       892
80   My three months review of Coca-Cola Diet Coke:...    1529       655
98   Comparing Microsoft Surface Laptop to the comp...     762       308
106  Comparing Coca-Cola Coke Zero to the competiti...    1792       625

In [17]:
# ============================================
# INSPECT USERS DATASET
# ============================================

print("Users columns:")
print(users.columns.tolist())

print("\nUsers shape:")
print(users.shape)

print("\nUsers sample:")
print(users.head(10))

print("\nUsers missing values:")
print(users.isna().sum())

Users columns:
['user_id', 'location', 'language', 'account_created', 'follower_count']

Users shape:
(1500, 5)

Users sample:
         user_id                location language account_created  \
0  user_guglt5jp         Berlin, Germany       ja      2023-10-23
1  user_b1p3wz81         Munich, Germany       zh      2023-05-06
2  user_jm2grmis              Dubai, UAE       en      2023-01-03
3  user_ykoqww5l           Paris, France       fr      2023-10-11
4  user_3zzvv8vp        Los Angeles, USA       ru      2023-05-23
5  user_s4nmuyvf           Mumbai, India       zh      2023-03-17
6  user_9vo7he3z  Rio de Janeiro, Brazil       en      2023-12-01
7  user_guruu55k     Mexico City, Mexico       en      2023-03-30
8  user_8nvzxsuj       Vancouver, Canada       es      2023-12-03
9  user_rgmvy3e1              London, UK       ja      2023-12-21

   follower_count
0           38963
1           24644
2           45842
3             665
4           42908
5           43412
6           36257
7           11260
8           36383
9           13458

Users missing values:
user_id            0
location           0
language           0
account_created    0
follower_count     0
dtype: int64

In [18]:
# ============================================
# INVESTIGATE MISSING TEXT CONTENT
# ============================================

text_missing = posts["text_content"].isna()

print("Total rows:", len(posts))
print("Missing text:", text_missing.sum())
print("Missing text %:", round(text_missing.mean() * 100, 2))

print("\nMissing text by platform:")
print(
    posts.groupby("platform", dropna=False)["text_content"]
    .agg(
        total_rows="size",
        missing_text=lambda x: x.isna().sum()
    )
)

print("\nSample rows with missing text:")
print(
    posts[text_missing][
        ["post_id", "user_id", "platform",
         "likes", "shares", "comments", "timestamp"]
    ].head(15)
)

Total rows: 12360
Missing text: 1746
Missing text %: 14.13

Missing text by platform:
           total_rows  missing_text
platform
Facebook         2135           298
Instagram        2038           287
Reddit           2086           314
Twitter          2119           310
YouTube          2136           297
NaN              1846           240

Sample rows with missing text:
         post_id        user_id   platform   likes  shares  comments  \
15  k9tvoyfmg8az  user_kf84zwv2   Facebook  4153.0     450       319
21  0eupqhh38ego  user_261d32en  Instagram  2900.0     186       978
25  jhzjp26xujxh  user_lpaf67a1    YouTube  3136.0     533       190
33  bm0zjjwqdjdt  user_wolyc68e    Twitter  2712.0    1150       436
36  aq3dtllhs6dr  user_2a5282v7    YouTube     NaN     197        21
38  1fu318s17aoz  user_vdzbq60d    YouTube  1690.0    1600       304
44  juovcq3m427s  user_h39vyus8        NaN  2127.0    1426       794
57  6ix3i5q2grjy  user_a7y7wdlm   Facebook   392.0     329       437
64  rcmwfuxl5rq7  user_4mf7je2u  Instagram  2012.0     638       664
70  62q3q1y4rvye  user_ja1dmtpu   Facebook     NaN    1594       365
74  mqrwtcmg6k9v  user_1rcpzj4g   Facebook  4376.0     950       864
76  6r49ob2s2vbd  user_zp2gw1bo  Instagram  3813.0     620       553
77  o70j2gzc3kkw  user_ztrgkwrt   Facebook     NaN    1035       892
83  w0lnzrqoiyej  user_hen7rrkk        NaN  1127.0    1837       151
89  59gdx6c1r4pz  user_eh4ki1e0        NaN  2170.0     616       911

              timestamp
15           1740278648
21           1742357104
25           1715414900
33  2024-06-15T07:07:50
36           04-10-2024
38           1738355111
44           1736206650
57  2024-06-15T11:51:58
64  2024-06-21T00:25:10
70           03-02-2025
74  2024-08-07T18:19:36
76           11-12-2024
77           1719830649
83  2025-02-09T04:37:44
89  2025-03-15T12:31:41

In [19]:
# ============================================
# CHECK WHETHER MISSING TEXT HAS OTHER PATTERN
# ============================================

print("\nMissing text vs available text:")
print(
    posts.groupby(text_missing)[["likes", "shares", "comments"]]
    .mean()
)

print("\nMissing text by platform (%):")

platform_text = posts.groupby(
    "platform",
    dropna=False
)["text_content"].agg(
    total_rows="size",
    missing_text=lambda x: x.isna().sum()
)

platform_text["missing_rate_%"] = (
    platform_text["missing_text"]
    / platform_text["total_rows"] * 100
).round(2)

print(platform_text)

Missing text vs available text:
                    likes       shares    comments
text_content
False         2488.953810  1003.420294  503.571321
True          2516.022388  1020.744559  507.186140

Missing text by platform (%):
           total_rows  missing_text  missing_rate_%
platform
Facebook         2135           298           13.96
Instagram        2038           287           14.08
Reddit           2086           314           15.05
Twitter          2119           310           14.63
YouTube          2136           297           13.90
NaN              1846           240           13.00

In [20]:
# ============================================
# TIMESTAMP FORMAT ANALYSIS
# ============================================

print("Timestamp missing:", posts["timestamp"].isna().sum())
print("Total timestamps:", posts["timestamp"].notna().sum())

# Detect timestamp format
def detect_timestamp_format(value):
    if pd.isna(value):
        return "Missing"
    
    value = str(value).strip()
    
    if value.isdigit():
        return "Unix"
    elif "T" in value:
        return "ISO"
    elif "-" in value:
        return "DMY"
    else:
        return "Other"

timestamp_formats = posts["timestamp"].apply(
    detect_timestamp_format
)

print("\nTimestamp formats:")
print(timestamp_formats.value_counts())

Timestamp missing: 0
Total timestamps: 12360

Timestamp formats:
timestamp
ISO     4950
Unix    3788
DMY     3622
Name: count, dtype: int64

In [21]:
# ============================================
# TEST TIMESTAMP PARSING
# ============================================

def parse_timestamp(value):
    if pd.isna(value):
        return pd.NaT
    
    value = str(value).strip()
    
    # Unix timestamp
    if value.isdigit():
        return pd.to_datetime(
            int(value),
            unit="s",
            errors="coerce"
        )
    
    # ISO format
    if "T" in value:
        return pd.to_datetime(
            value,
            errors="coerce"
        )
    
    # DMY format
    return pd.to_datetime(
        value,
        format="%d-%m-%Y",
        errors="coerce"
    )

parsed_timestamps = posts["timestamp"].apply(parse_timestamp)

print("Invalid/unparseable timestamps:")
print(parsed_timestamps.isna().sum())

print("\nDate range:")
print("Minimum:", parsed_timestamps.min())
print("Maximum:", parsed_timestamps.max())

Invalid/unparseable timestamps:
0

Date range:
Minimum: 2024-05-01 00:00:00
Maximum: 2025-04-30 21:57:10

In [22]:
print("\nSample converted timestamps:")
print(
    pd.DataFrame({
        "original": posts["timestamp"],
        "parsed": parsed_timestamps
    }).head(20)
)

Sample converted timestamps:
               original              parsed
0            25-09-2024 2024-09-25 00:00:00
1            1722528840 2024-08-01 16:14:00
2   2025-04-13T20:12:18 2025-04-13 20:12:18
3            10-09-2024 2024-09-10 00:00:00
4            31-05-2024 2024-05-31 00:00:00
5            24-01-2025 2025-01-24 00:00:00
6            1719394663 2024-06-26 09:37:43
7   2025-03-27T13:44:32 2025-03-27 13:44:32
8   2024-05-05T05:52:34 2024-05-05 05:52:34
9            11-02-2025 2025-02-11 00:00:00
10  2024-06-11T14:54:47 2024-06-11 14:54:47
11           1736393335 2025-01-09 03:28:55
12           1725467245 2024-09-04 16:27:25
13           15-02-2025 2025-02-15 00:00:00
14           1731343668 2024-11-11 16:47:48
15           1740278648 2025-02-23 02:44:08
16           14-12-2024 2024-12-14 00:00:00
17           1716471784 2024-05-23 13:43:04
18           1733293947 2024-12-04 06:32:27
19           1732652943 2024-11-26 20:29:03

In [23]:
# ============================================
# DUPLICATE POST_ID VALIDATION
# ============================================

duplicate_ids = posts[
    posts["post_id"].duplicated(keep=False)
]["post_id"]

print("Rows with duplicated post_id:", len(duplicate_ids))
print("Unique duplicated post_ids:", duplicate_ids.nunique())

# Check whether duplicated post_ids have identical rows
duplicate_groups = posts[
    posts["post_id"].isin(duplicate_ids)
].groupby("post_id").nunique()

print("\nMaximum number of different values within a duplicated post_id:")
print(duplicate_groups.max())

print("\nAre duplicated post_id groups identical?")
print((duplicate_groups <= 1).all())

Rows with duplicated post_id: 712
Unique duplicated post_ids: 352

Maximum number of different values within a duplicated post_id:
user_id               1
platform              1
text_content          1
timestamp             1
likes                 1
shares                1
comments              1
likes_original        1
likes_was_negative    1
dtype: int64

Are duplicated post_id groups identical?
user_id               True
platform              True
text_content          True
timestamp             True
likes                 True
shares                True
comments              True
likes_original        True
likes_was_negative    True
dtype: bool

In [24]:
# ============================================
# REMOVE EXACT DUPLICATE RECORDS
# ============================================

before_duplicates = len(posts)

posts = posts.drop_duplicates().copy()

after_duplicates = len(posts)

print("Rows before duplicate removal:", before_duplicates)
print("Rows after duplicate removal:", after_duplicates)
print("Duplicate rows removed:", before_duplicates - after_duplicates)

print("\nRemaining duplicate rows:")
print(posts.duplicated().sum())

print("\nRemaining duplicated post_ids:")
print(posts["post_id"].duplicated().sum())

Rows before duplicate removal: 12360
Rows after duplicate removal: 12000
Duplicate rows removed: 360

Remaining duplicate rows:
0

Remaining duplicated post_ids:
0

In [25]:
# ============================================
# STANDARDIZE TIMESTAMPS
# ============================================

posts["timestamp_original"] = posts["timestamp"]

posts["timestamp_clean"] = posts["timestamp"].apply(parse_timestamp)

print("Invalid timestamps after parsing:",
      posts["timestamp_clean"].isna().sum())

print("\nClean timestamp range:")
print("Minimum:", posts["timestamp_clean"].min())
print("Maximum:", posts["timestamp_clean"].max())

print("\nTimestamp sample:")
print(
    posts[["timestamp_original", "timestamp_clean"]].head(10)
)

Invalid timestamps after parsing: 0

Clean timestamp range:
Minimum: 2024-05-01 00:00:00
Maximum: 2025-04-30 21:57:10

Timestamp sample:
    timestamp_original     timestamp_clean
0           25-09-2024 2024-09-25 00:00:00
1           1722528840 2024-08-01 16:14:00
2  2025-04-13T20:12:18 2025-04-13 20:12:18
3           10-09-2024 2024-09-10 00:00:00
4           31-05-2024 2024-05-31 00:00:00
5           24-01-2025 2025-01-24 00:00:00
6           1719394663 2024-06-26 09:37:43
7  2025-03-27T13:44:32 2025-03-27 13:44:32
8  2024-05-05T05:52:34 2024-05-05 05:52:34
9           11-02-2025 2025-02-11 00:00:00

In [26]:
# ============================================
# CLEAN HTML-ENCODED TEXT
# ============================================

from html import unescape

posts["text_content_original"] = posts["text_content"]

posts["text_content"] = posts["text_content"].apply(
    lambda x: unescape(x) if pd.notna(x) else x
)

print("HTML entity occurrences remaining:")
print(posts["text_content"].str.contains(
    "&amp;",
    na=False
).sum())

print("\nSample cleaned text:")
print(
    posts[["text_content_original", "text_content"]]
    .loc[
        posts["text_content_original"].str.contains(
            "&amp;",
            na=False
        )
    ]
    .head(10)
)

HTML entity occurrences remaining:
0

Sample cleaned text:
                                 text_content_original  \
0    Bummed out with my new Air Max from Nike! Abso...
19   Has anyone else experienced delivery delays wi...
52   Confused about with my new Sienna from Toyota!...
63   Comparing Apple iMac to the competition. Highl...
71   How do I fix about Google's Pixel Watch? @Cele...
91                                           NULL&amp;
97   Has anyone else experienced software bugs with...
111  My one week review of Coca-Cola Fanta: As expe...
116  Adidas HolidaySpecial is standard! Can't wait ...
128  Thrilled with my new Yeezy from Adidas! Had is...

                                          text_content
0    Bummed out with my new Air Max from Nike! Abso...
19   Has anyone else experienced delivery delays wi...
52   Confused about with my new Sienna from Toyota!...
63   Comparing Apple iMac to the competition. Highl...
71   How do I fix about Google's Pixel Watch? @Cele...
91                                               NULL&
97   Has anyone else experienced software bugs with...
111  My one week review of Coca-Cola Fanta: As expe...
116  Adidas HolidaySpecial is standard! Can't wait ...
128  Thrilled with my new Yeezy from Adidas! Had is...

In [27]:
# ============================================
# CLEANING VALIDATION
# ============================================

print("Final rows:", len(posts))
print("Final columns:", len(posts.columns))

print("\nMissing values:")
print(posts.isna().sum())

print("\nNegative likes remaining:",
      (posts["likes"] < 0).sum())

print("\nDuplicate rows remaining:",
      posts.duplicated().sum())

print("\nDuplicate post_ids remaining:",
      posts["post_id"].duplicated().sum())

Final rows: 12000
Final columns: 13

Missing values:
post_id                     0
user_id                     0
platform                 1784
text_content             1688
timestamp                   0
likes                    1814
shares                      0
comments                    0
likes_original           1814
likes_was_negative          0
timestamp_original          0
timestamp_clean             0
text_content_original    1688
dtype: int64

Negative likes remaining: 0

Duplicate rows remaining: 0

Duplicate post_ids remaining: 0

In [28]:
# ============================================
# FINAL CLEANING VALIDATION
# ============================================

print("=" * 60)
print("FINAL DATASET VALIDATION")
print("=" * 60)

print("\nDataset shape:")
print(posts.shape)

print("\nDuplicate rows:")
print(posts.duplicated().sum())

print("\nDuplicate post_ids:")
print(posts["post_id"].duplicated().sum())

print("\nNegative likes:")
print((posts["likes"] < 0).sum())

print("\nInvalid timestamps:")
print(posts["timestamp_clean"].isna().sum())

print("\nRemaining HTML entities:")
print(
    posts["text_content"]
    .str.contains("&amp;", na=False)
    .sum()
)

print("\nMissing values:")
print(posts.isna().sum())

print("\nFinal columns:")
print(posts.columns.tolist())

============================================================
FINAL DATASET VALIDATION
============================================================

Dataset shape:
(12000, 13)

Duplicate rows:
0

Duplicate post_ids:
0

Negative likes:
0

Invalid timestamps:
0

Remaining HTML entities:
0

Missing values:
post_id                     0
user_id                     0
platform                 1784
text_content             1688
timestamp                   0
likes                    1814
shares                      0
comments                    0
likes_original           1814
likes_was_negative          0
timestamp_original          0
timestamp_clean             0
text_content_original    1688
dtype: int64

Final columns:
['post_id', 'user_id', 'platform', 'text_content', 'timestamp', 'likes', 'shares', 'comments', 'likes_original', 'likes_was_negative', 'timestamp_original', 'timestamp_clean', 'text_content_original']

In [29]:
# ============================================
# EXPORT CLEANED DATASET - AUDIT VERSION
# ============================================

from pathlib import Path

OUTPUT_DIR = BASE_DIR / "data" / "processed"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

AUDIT_OUTPUT = OUTPUT_DIR / "posts_cleaned_audit.csv"

posts.to_csv(AUDIT_OUTPUT, index=False)

print("Saved successfully!")
print("File:", AUDIT_OUTPUT)
print("Rows:", len(posts))
print("Columns:", len(posts.columns))

Saved successfully!
File: c:\Users\Jivan\OneDrive\Desktop\projectS\DATA-VORTEX-SOCIAL-ENGINE\data\processed\posts_cleaned_audit.csv
Rows: 12000
Columns: 13

In [30]:
# ============================================
# CREATE ANALYTICAL CLEAN DATASET
# ============================================

clean_posts = posts.drop(
    columns=[
        "likes_original",
        "likes_was_negative",
        "timestamp_original",
        "text_content_original"
    ]
).copy()

# Use standardized timestamp
clean_posts["timestamp"] = clean_posts["timestamp_clean"]

# Remove helper column
clean_posts = clean_posts.drop(
    columns=["timestamp_clean"]
)

print("Clean dataset shape:", clean_posts.shape)

print("\nColumns:")
print(clean_posts.columns.tolist())

print("\nDuplicates:", clean_posts.duplicated().sum())
print("Duplicate post_ids:", clean_posts["post_id"].duplicated().sum())

Clean dataset shape: (12000, 8)

Columns:
['post_id', 'user_id', 'platform', 'text_content', 'timestamp', 'likes', 'shares', 'comments']

Duplicates: 0
Duplicate post_ids: 0

In [31]:
# ============================================
# EXPORT FINAL CLEAN DATASET
# ============================================

CLEAN_OUTPUT = OUTPUT_DIR / "posts_cleaned.csv"

clean_posts.to_csv(CLEAN_OUTPUT, index=False)

print("Final cleaned dataset saved!")
print("File:", CLEAN_OUTPUT)
print("Rows:", len(clean_posts))
print("Columns:", len(clean_posts.columns))

Final cleaned dataset saved!
File: c:\Users\Jivan\OneDrive\Desktop\projectS\DATA-VORTEX-SOCIAL-ENGINE\data\processed\posts_cleaned.csv
Rows: 12000
Columns: 8